spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.163.com
    username: pcx_online@163.com
    password: JUXCNNPNVOMZVZHA
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 20MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    file:
      keyId: 这是id
      keySecret: 这是密码
      endpoint: 这是地域节点
      bucketName: 这是bucketName
